# Windows (PowerShell)
New-Item -Path ".streamlit\secrets.toml" -ItemType File

# Mac/Linux (Terminal)
touch .streamlit/secrets.toml

GROQ_API_KEY = "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"
